export const MEALS = [
  {
    id: 'breakfast',
    time: '7:00 AM',
    name: 'Breakfast',
    items: ['6 eggs', '2 wheat bread slices', '1.5 tbsp peanut butter'],
    protein: 48,
    calories: 734,
    carbs: 45,
    fat: 40,
  },
  {
    id: 'mid_morning',
    time: '10:30 AM',
    name: 'Mid-Morning',
    items: ['1 scoop whey protein', '1 banana'],
    protein: 25,
    calories: 235,
    carbs: 27,
    fat: 3,
  },
  {
    id: 'lunch',
    time: '1:00 PM',
    name: 'Lunch',
    items: ['150g chicken or fish (alternate daily)', '1 cup rice', 'Sabzi / dal'],
    note: 'Rest day: use ½ cup rice',
    protein: 44,
    calories: 475,
    carbs: 57,
    fat: 8,
  },
  {
    id: 'evening',
    time: '4:00 PM',
    name: 'Evening Snack',
    items: ['200g Greek yogurt', '20g almonds'],
    protein: 16,
    calories: 255,
    carbs: 12,
    fat: 16,
  },
  {
    id: 'dinner',
    time: '7:30 PM',
    name: 'Dinner',
    items: ['1 scoop whey protein', '2 chapati', 'Dal / sabzi'],
    protein: 35,
    calories: 425,
    carbs: 49,
    fat: 10,
  },
];

export const DAILY_TARGETS = {
  calories: 2370,
  protein: 152,
  carbs: 180,
  fat: 75,
  tdee: 2600,
  deficit: 230,
};
